// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Vector3Stamped.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "Vector3Stamped.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

#define geometry_msgs_msg_Vector3_max_cdr_typesize 24ULL;
#define builtin_interfaces_msg_Time_max_cdr_typesize 8ULL;
#define geometry_msgs_msg_Vector3Stamped_max_cdr_typesize 296ULL;
#define std_msgs_msg_Header_max_cdr_typesize 268ULL;
#define geometry_msgs_msg_Vector3_max_key_cdr_typesize 0ULL;
#define builtin_interfaces_msg_Time_max_key_cdr_typesize 0ULL;
#define geometry_msgs_msg_Vector3Stamped_max_key_cdr_typesize 0ULL;
#define std_msgs_msg_Header_max_key_cdr_typesize 0ULL;

geometry_msgs::msg::Vector3Stamped::Vector3Stamped()
{
    // std_msgs::msg::Header m_header

    // geometry_msgs::msg::Vector3 m_vector


}

geometry_msgs::msg::Vector3Stamped::~Vector3Stamped()
{


}

geometry_msgs::msg::Vector3Stamped::Vector3Stamped(
        const Vector3Stamped& x)
{
    m_header = x.m_header;
    m_vector = x.m_vector;
}

geometry_msgs::msg::Vector3Stamped::Vector3Stamped(
        Vector3Stamped&& x) noexcept 
{
    m_header = std::move(x.m_header);
    m_vector = std::move(x.m_vector);
}

geometry_msgs::msg::Vector3Stamped& geometry_msgs::msg::Vector3Stamped::operator =(
        const Vector3Stamped& x)
{

    m_header = x.m_header;
    m_vector = x.m_vector;

    return *this;
}

geometry_msgs::msg::Vector3Stamped& geometry_msgs::msg::Vector3Stamped::operator =(
        Vector3Stamped&& x) noexcept
{

    m_header = std::move(x.m_header);
    m_vector = std::move(x.m_vector);

    return *this;
}

bool geometry_msgs::msg::Vector3Stamped::operator ==(
        const Vector3Stamped& x) const
{

    return (m_header == x.m_header && m_vector == x.m_vector);
}

bool geometry_msgs::msg::Vector3Stamped::operator !=(
        const Vector3Stamped& x) const
{
    return !(*this == x);
}

size_t geometry_msgs::msg::Vector3Stamped::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_Vector3Stamped_max_cdr_typesize;
}

size_t geometry_msgs::msg::Vector3Stamped::getCdrSerializedSize(
        const geometry_msgs::msg::Vector3Stamped& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += std_msgs::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += geometry_msgs::msg::Vector3::getCdrSerializedSize(data.vector(), current_alignment);

    return current_alignment - initial_alignment;
}

void geometry_msgs::msg::Vector3Stamped::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_vector;

}

void geometry_msgs::msg::Vector3Stamped::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_vector;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void geometry_msgs::msg::Vector3Stamped::header(
        const std_msgs::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void geometry_msgs::msg::Vector3Stamped::header(
        std_msgs::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const std_msgs::msg::Header& geometry_msgs::msg::Vector3Stamped::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
std_msgs::msg::Header& geometry_msgs::msg::Vector3Stamped::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member vector
 * @param _vector New value to be copied in member vector
 */
void geometry_msgs::msg::Vector3Stamped::vector(
        const geometry_msgs::msg::Vector3& _vector)
{
    m_vector = _vector;
}

/*!
 * @brief This function moves the value in member vector
 * @param _vector New value to be moved in member vector
 */
void geometry_msgs::msg::Vector3Stamped::vector(
        geometry_msgs::msg::Vector3&& _vector)
{
    m_vector = std::move(_vector);
}

/*!
 * @brief This function returns a constant reference to member vector
 * @return Constant reference to member vector
 */
const geometry_msgs::msg::Vector3& geometry_msgs::msg::Vector3Stamped::vector() const
{
    return m_vector;
}

/*!
 * @brief This function returns a reference to member vector
 * @return Reference to member vector
 */
geometry_msgs::msg::Vector3& geometry_msgs::msg::Vector3Stamped::vector()
{
    return m_vector;
}


size_t geometry_msgs::msg::Vector3Stamped::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    static_cast<void>(current_alignment);
    return geometry_msgs_msg_Vector3Stamped_max_key_cdr_typesize;
}

bool geometry_msgs::msg::Vector3Stamped::isKeyDefined()
{
    return false;
}

void geometry_msgs::msg::Vector3Stamped::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
}


