#!/usr/bin/env python
import os
env = SConscript("../godot-cpp/SConstruct")

if env["target"] == "template_debug":
    suffix = "_debug"
else:
    suffix = "_release"

# mavsdk
env.Append(CPPPATH=["C:/Users/timet/Documents/Dev/GoMavSimulator/extensions/build/mavsdk/MAVSDK-prefix/src/MAVSDK-build/install/include"])
env.Append(LIBPATH=["C:/Users/timet/Documents/Dev/GoMavSimulator/extensions/build/mavsdk/MAVSDK-prefix/src/MAVSDK-build/install/lib"])
env.Append(LIBS=["mavsdk"])

# mavsdk binding 
env.Append(CPPPATH=["include"])
sources = Glob("src/*.cpp")

# exports
library = env.SharedLibrary(
    target="../../addons/mavsdk/bin/" + "mavsdk_binding" + suffix,
    source=sources,
)

Default(library)
